routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// email verify
Route::get('verify-registration/{id}', ['as' => 'verify.registration', 'uses' => 'Auth\RegisterController@verifyByUser']);

//Social Login

Route::get('/auth/{social}','Auth\LoginController@socialLogin')->where('social','twitter|facebook|linkedin|google|github|bitbucket');
Route::get('/auth/{social}/callback','Auth\LoginController@handleProviderCallback')->where('social','twitter|facebook|linkedin|google|github|bitbucket');


// Member Users

Route::group([
    'prefix' => 'member',
    'namespace' => 'Member',
    'middleware' => ['auth', 'role:member'],
    'as' => 'member.'
], function () {
    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
});


// Management or Admin Users

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => ['auth', 'role:admin'],
    'as' => 'admin.'
], function () {
    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
    Route::resource('roles','RoleController');
    Route::resource('permissions','PermissionController');
    Route::resource('users','UserController');

});

app/Models/Role.php
<?php

namespace App\Models;

use Zizaco\Entrust\EntrustRole;
use Illuminate\Support\Facades\Config;


class Role extends EntrustRole
{
    protected $fillable = ['name','display_name','is_active','description'];

    /**
     * Many-to-Many relations with the user model.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function users()
    {
        return $this->belongsToMany(Config::get('auth.providers.users.model'), Config::get('entrust.role_user_table'),Config::get('entrust.role_foreign_key'),Config::get('entrust.user_foreign_key'));
    }
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Permission;
use App\Models\Role;
use Dompdf\Exception;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['roles'] = Role::latest()->paginate(10);

        return view('admin.roles.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['permissions'] = Permission::get();

        return view('admin.roles.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles',
            'display_name' => 'required|unique:roles',
        ]);

        try{
            $role = new Role();
            $role->name = strtolower(str_replace(' ', '_', $request->input('name')));
            $role->display_name = $request->input('display_name');;
            $role->description  = $request->input('description');; // optional
            $role->save();

            $role->perms()->sync($request->input('permissions'));

            return back()->with('status', ['type' => 'success', 'message' => 'Successfully Saved']);
        }catch( Exception $exception ){
            return back()->with('status', ['type' => 'error', 'message' => 'Unable to Add']);
        }


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['permissions'] = Permission::get();
        $data['model']= $role = Role::findOrFail($id);
        $data['rolePermissions'] = $role->perms()->pluck('id')->toArray();

        return view('admin.roles.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles,name,'. $id,
            'display_name' => 'required|unique:roles,display_name,'. $id,
        ]);

        if(!Auth::user()->can('super-admin')) {
            return redirect()->back();
        }

        $role = Role::find($id);

        if($this->isModifiableRole($role->name)) {
            $role->name = strtolower(str_replace(' ', '_', $request->input('name')));
        }

        $role->display_name = $request->input('display_name');
        $role->description  = $request->input('description');
        $role->save();

        $role->perms()->sync($request->input('permissions'));

        return back()->with('status', ['type' => 'success', 'message' => 'Successfully Updated']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::find($id);

        if ($this->isModifiableRole($role->name)) {
            $role->delete();
        }

        return $this->index();
    }

    /**
     * Get restricted roles that can't be edited or deleted
     *
     * @return array
     */
    private function restrictedRoles()
    {
        return ['admin', 'developer', 'merchant', 'ambassador'];
    }

    /**
     * Check if role is editable or deletable
     *
     * @param $role
     * @return bool
     */
    private function isModifiableRole($role)
    {
        return !in_array($role, $this->restrictedRoles());
    }
}

resources/views/admin/roles/_form.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 1/1/2018
 * Time: 11:37 PM
 */
?>

@if(!isset($role))
<div class="row">
    <div class="col-md-6 col-lg-6  col-sm-12 col-xs-12 form-group {{ $errors->has('name') ? 'has-error' : '' }} ">
        {!! Form::label('name', 'Name') !!} <span class="required red"> * </span>
        <div class="form-group">
            {!! Form::text('name',null,['class'=>'form-control','placeholder'=>'Name']); !!}
        </div>
        {!! $errors->first('name', '<span class="help-block red"><strong>:message</strong></span>') !!}
    </div>
</div>
@endif

<div class="row">
    <div class="col-md-6 col-lg-6  col-sm-12 col-xs-12 form-group {{ $errors->has('display_name') ? 'has-error' : '' }} ">
        {!! Form::label('display_name', 'Display Name') !!} <span class="required red"> * </span>
        <div class="form-group">
            {!! Form::text('display_name',null,['class'=>'form-control','placeholder'=>'Display Name']); !!}
        </div>
        {!! $errors->first('display_name', '<span class="help-block red"><strong>:message</strong></span>') !!}
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-lg-6  col-sm-12 col-xs-12 form-group">
        {!! Form::label('description', 'Description') !!}
        <div class="form-group">
            {!! Form::textarea('description',null,['class'=>'form-control','placeholder'=>'Description', 'rows' =>2]); !!}
        </div>
        {!! $errors->first('description', '<span class="help-block red"><strong>:message</strong></span>') !!}
    </div>
</div>

<hr>
<h4>Permissions</h4>
<hr>
<div class="row">
@foreach($permissions as $key => $permission)
    <div class="col-md-3">
        <label>
            @if(isset($rolePermissions))
                <input type="checkbox" class="" value="{{ $permission->id }}" {{ in_array($permission->id, $rolePermissions) ? 'checked' : '' }} name="permissions[]"> {{ $permission->display_name }}
            @else
                <input type="checkbox" class="" value="{{ $permission->id }}" name="permissions[]"> {{ $permission->display_name }}
            @endif
        </label>
    </div>
@endforeach
</div>

<div class="row">
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 text-right">
        <button type="submit" class="btn green">Save</button>
        <button type="reset" class="btn red">Reset</button>
    </div>
</div>

resources/views/admin/roles/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 1/1/2018
 * Time: 11:38 PM
 */


$data['breadcrumb'] = [
    [
        'name' => 'Home',
        'href' => route('admin.dashboard'),
        'icon' => 'fa fa-home',
    ],
    [
        'name' => 'Roles',
        'href' => route('admin.roles.index'),
    ],
    [
        'name' => 'Add Role',
    ],
];

$data['data'] = [
    'name' => 'Roles',
    'title'=>'Add Role',
    'heading' => 'Add Role',
];

?>

@extends('admin.layout.master', $data)

@section('contents')
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">

            @include('common._alert')

            <div class="portlet light">

                <div class="portlet-body form">
                    {!! Form::open(['route' => 'admin.roles.store', 'method' => 'POST', 'role'=>'form' ]) !!}

                    <div class="form-body">
                        @include('admin.roles._form')
                    </div>

                    {!! Form::close() !!}
                </div>
                <!-- END SAMPLE FORM PORTLET-->
            </div>
        </div>
    </div>
@endsection

resources/views/admin/roles/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 1/1/2018
 * Time: 11:37 PM
 */


$data['breadcrumb'] = [
    [
        'name' => 'Home',
        'href' => route('admin.dashboard'),
        'icon' => 'fa fa-home',
    ],
    [
        'name' => 'Roles',
        'href' => route('admin.roles.index'),
    ],
    [
        'name' => 'Edit',
    ],
];

$data['data'] = [
    'name' => 'Roles',
    'title'=>'Edit Role',
    'heading' => 'Edit Role',
];

?>

@extends('admin.layout.master', $data)

@section('contents')
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
            <!-- BEGIN SAMPLE FORM PORTLET-->
            @include('common._alert')

            <div class="portlet light">

                <div class="portlet-body form">
                    {!! Form::model($model, ['route' => ['admin.roles.update', $model],  'method' => 'put']) !!}

                    <div class="form-body">
                        @include('admin.roles._form')
                    </div>

                    {!! Form::close() !!}
                </div>
                <!-- END SAMPLE FORM PORTLET-->
            </div>
        </div>
    </div>
@endsection

resources/views/admin/roles/index.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 1/1/2018
 * Time: 11:37 PM
 */


$data['breadcrumb'] = [
    [
        'name' => 'Home',
        'href' => route('admin.dashboard'),
        'icon' => 'fa fa-home',
    ],
    [
        'name' => 'Roles',
        'href' => route('admin.roles.index'),
    ],
    [
        'name' => 'Index',
    ],
];

$data['data'] = [
    'name' => 'Roles',
    'title'=>'List Of Roles',
    'heading' => 'List Of Roles',
];

?>

@extends('admin.layout.master', $data)

@section('contents')
    <div class="portlet light">

        <div class="portlet-body form">
            <a href="{{ route('admin.roles.create') }}" class="btn green"> <i class="fa fa-plus"> Add Role </i></a>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
    </div>
    <div class="row">
        <!-- BEGIN SAMPLE FORM PORTLET-->

        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
            <!-- BEGIN SAMPLE FORM PORTLET-->

            <div class="table-responsive">
                <table class="table table-striped">
                    <tr>
                        <td> # </td>
                        <td> Display Name </td>
                        <td> Name </td>
                        <td> Manage </td>
                    </tr>
                    @foreach( $roles as $role)
                        <tr>
                            <td> {{ $loop->index + 1 }} </td>
                            <td> {{ $role->display_name }} </td>
                            <td> {{ $role->name }} </td>
                            <td>
                                <a href="{{ route('admin.roles.edit', $role->id) }}" class="btn btn-xs btn-success">
                                    <i class="fa fa-pencil"></i>
                                </a>

                                <a href="javascript:void(0);" class="btn btn-xs btn-danger delete-confirm" data-target="{{  route('admin.roles.destroy', $role->id) }}">
                                    <i class="fa fa-times"></i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    <tr>
                        <td colspan="4" class="text-right">
                            {{ $roles->links() }}
                        </td>
                    </tr>

                </table>
            </div>
        </div>
    </div>
@endsection