routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// email verify
Route::get('verify-registration/{id}', ['as' => 'verify.registration', 'uses' => 'Auth\RegisterController@verifyByUser']);

//Social Login

Route::get('/auth/{social}','Auth\LoginController@socialLogin')->where('social','twitter|facebook|linkedin|google|github|bitbucket');
Route::get('/auth/{social}/callback','Auth\LoginController@handleProviderCallback')->where('social','twitter|facebook|linkedin|google|github|bitbucket');


// Member Users

Route::group([
    'prefix' => 'member',
    'namespace' => 'Member',
    'middleware' => ['auth', 'role:member'],
    'as' => 'member.'
], function () {
    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
});


// Management or Admin Users

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => ['auth', 'role:admin'],
    'as' => 'admin.'
], function () {
    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
    Route::resource('roles','RoleController');
    Route::resource('permissions','PermissionController');
    Route::resource('users','UserController');

});

resources/views/admin/partials/breadcrumb.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 12/2/2017
 * Time: 10:38 PM
 */
?>

<!-- BEGIN PAGE BAR -->

@isset($breadcrumb)

<div class="page-bar">
    <ul class="page-breadcrumb">

            @foreach($breadcrumb as $b)
                <li class="{{ $loop->last ? 'active' : '' }}">
                    @if(isset($b['href']))
                        <a href="{{$b['href']}}">
                            <i class="{{ isset($b['icon']) ? $b['icon'] : '' }}"></i>
                            {{$b['name']}}
                        </a>
                        <i class="fa fa-circle"></i>
                    @else
                        <strong>{{$b['name']}}</strong>
                    @endif
                </li>
            @endforeach
    </ul>
</div>
<!-- END PAGE BAR --

     <!-- BEGIN PAGE TITLE-->
@if( isset($data['heading']) )
<h1 class="page-title">
    {{ $data['heading'] ? $data['heading'] : $data['name']}}
</h1>
@endif


@endisset
<!-- END PAGE TITLE-->

resources/views/admin/partials/footer.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 12/2/2017
 * Time: 10:17 PM
 */
?>

<!-- BEGIN FOOTER -->
<div class="page-footer">
    <div class="page-footer-inner"> 2017 &copy; Login System By
        <a target="_blank" href="http://www.mobarokhossen.me"> Mobarok Hossen</a> &nbsp;|&nbsp; Software Engineer
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>
<!-- END FOOTER -->

resources/views/admin/partials/quick-nav.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 12/2/2017
 * Time: 10:27 PM
 */
?>


{{--<!-- BEGIN QUICK NAV -->--}}
{{--<nav class="quick-nav">--}}
    {{--<a class="quick-nav-trigger" href="#0">--}}
        {{--<span aria-hidden="true"></span>--}}
    {{--</a>--}}
    {{--<ul>--}}
        {{--<li>--}}
            {{--<a href="https://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes" target="_blank" class="active">--}}
                {{--<span>Purchase Metronic</span>--}}
                {{--<i class="icon-basket"></i>--}}
            {{--</a>--}}
        {{--</li>--}}
        {{--<li>--}}
            {{--<a href="https://themeforest.net/item/metronic-responsive-admin-dashboard-template/reviews/4021469?ref=keenthemes" target="_blank">--}}
                {{--<span>Customer Reviews</span>--}}
                {{--<i class="icon-users"></i>--}}
            {{--</a>--}}
        {{--</li>--}}
        {{--<li>--}}
            {{--<a href="http://keenthemes.com/showcast/" target="_blank">--}}
                {{--<span>Showcase</span>--}}
                {{--<i class="icon-user"></i>--}}
            {{--</a>--}}
        {{--</li>--}}
        {{--<li>--}}
            {{--<a href="http://keenthemes.com/metronic-theme/changelog/" target="_blank">--}}
                {{--<span>Changelog</span>--}}
                {{--<i class="icon-graph"></i>--}}
            {{--</a>--}}
        {{--</li>--}}
    {{--</ul>--}}
    {{--<span aria-hidden="true" class="quick-nav-bg"></span>--}}
{{--</nav>--}}
{{--<div class="quick-nav-overlay"></div>--}}
{{--<!-- END QUICK NAV -->--}}

resources/views/admin/partials/script.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 12/2/2017
 * Time: 10:11 PM
 */
?>

<!--[if lt IE 9]>
<script src="{{asset('admin/global/plugins/respond.min.js')}}"></script>
<script src="{{asset('admin/global/plugins/excanvas.min.js')}}"></script>
<script src="{{asset('admin/global/plugins/ie8.fix.min.js')}}"></script>
<![endif]-->
<!-- BEGIN CORE PLUGINS -->
<script src="{{asset('admin/global/plugins/jquery.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/bootstrap/js/bootstrap.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/js.cookie.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/jquery.blockui.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js')}}" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="{{asset('admin/global/plugins/fancybox/source/jquery.fancybox.pack.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/jquery-file-upload/js/vendor/jquery.ui.widget.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/jquery-file-upload/js/vendor/tmpl.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/jquery-file-upload/js/vendor/load-image.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/jquery-file-upload/js/vendor/canvas-to-blob.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/jquery-file-upload/blueimp-gallery/jquery.blueimp-gallery.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/jquery-file-upload/js/jquery.iframe-transport.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/jquery-file-upload/js/jquery.fileupload.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/jquery-file-upload/js/jquery.fileupload-process.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/jquery-file-upload/js/jquery.fileupload-image.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/jquery-file-upload/js/jquery.fileupload-audio.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/jquery-file-upload/js/jquery.fileupload-video.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/jquery-file-upload/js/jquery.fileupload-validate.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/jquery-file-upload/js/jquery.fileupload-ui.js')}}" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->

<!-- BEGIN PAGE LEVEL PLUGINS -->

<script src="{{ asset('admin/global/plugins/jqueryUI/jquery-ui.min.js') }}"></script>
<script src="{{ asset('admin/global/plugins/selectboxit/jquery.selectBoxIt.min.js') }}"></script>
<script src="{{asset('admin/global/plugins/select2/js/select2.full.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/jquery-validation/js/jquery.validate.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/jquery-validation/js/additional-methods.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/ckeditor/ckeditor.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/bootstrap-markdown/lib/markdown.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/global/plugins/bootstrap-markdown/js/bootstrap-markdown.js')}}" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->

<!-- SweetAlert -->
{{--<script src="{{ asset('plugins/sweetalert/sweetalert.min.js') }}"></script>--}}
<!-- DataTables -->
<script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
<!-- DataTables -->
<script src="{{ asset('plugins/datatables/dataTables.bootstrap.min.js') }}"></script>

@stack('scripts')

<!-- BEGIN THEME GLOBAL SCRIPTS -->
<script src="{{asset('admin/global/scripts/app.min.js')}}" type="text/javascript"></script>
<!-- END THEME GLOBAL SCRIPTS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{{asset('admin/apps/scripts/inbox.min.js')}}" type="text/javascript"></script>

<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{{asset('admin/pages/scripts/form-validation.min.js')}}" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<!-- Custom javascript -->
<script src="{{ asset('admin/js/bootbox.min.js') }}"></script>
<script src="{{ asset('admin/js/application.js') }}"></script>

<!-- END PAGE LEVEL SCRIPTS -->
<!-- BEGIN THEME LAYOUT SCRIPTS -->
<script src="{{asset('admin/layouts/layout/scripts/layout.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/layouts/global/scripts/quick-sidebar.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin/layouts/global/scripts/quick-nav.min.js')}}" type="text/javascript"></script>
<!-- END THEME LAYOUT SCRIPTS -->

<script>
    $(document).ready(function()
    {

        $('#clickmewow').click(function()
        {
            $('#radio1003').attr('checked', 'checked');
        });
    })
</script>

resources/views/admin/partials/sidebar.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 12/2/2017
 * Time: 10:16 PM
 */
?>

<!-- BEGIN SIDEBAR -->
<div class="page-sidebar-wrapper">
    <div class="page-sidebar navbar-collapse collapse">
          <ul class="page-sidebar-menu  page-header-fixed " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">
             <li class="sidebar-toggler-wrapper hide">
                <div class="sidebar-toggler">
                    <span></span>
                </div>
            </li>
            <li class="sidebar-search-wrapper">
                <form class="sidebar-search  " action="#" method="POST">
                    <a href="javascript:;" class="remove">
                        <i class="icon-close"></i>
                    </a>
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <a href="javascript:;" class="btn submit">
                                <i class="icon-magnifier"></i>
                            </a>
                        </span>
                    </div>
                </form>
                <!-- END RESPONSIVE QUICK SEARCH FORM -->
            </li>
            <li class="nav-item start ">
                <a href="{{route('admin.dashboard')}}" class="nav-link nav-toggle">
                    <i class="fa fa-television"></i>
                    <span class="title">Dashboard</span>
                </a>
            </li>


              <li class="heading">
                  {{--<i class="icon-settings"></i> --}}
                  <h3 class="uppercase">Settings</h3>
              </li>
              <li class="nav-item  ">
                  <a href="{{ route('admin.roles.index') }}" class="nav-link nav-toggle">
                      <i class="fa fa-tasks"></i>
                      <span class="title">Roles</span>
                  </a>
              </li>
              <li class="nav-item ">
                  <a href="{{ route('admin.permissions.index') }}" class="nav-link nav-toggle">
                      <i class="icon-lock"></i>
                      <span class="title">Permissions</span>
                  </a>
              </li>
          </ul>
        <!-- END SIDEBAR MENU -->
    </div>
    <!-- END SIDEBAR -->
</div>
<!-- END SIDEBAR -->

resources/views/admin/partials/style.blade.php
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
<link href="{{asset('admin/global/plugins/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('admin/global/plugins/simple-line-icons/simple-line-icons.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('admin/global/plugins/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('admin/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css')}}" rel="stylesheet" type="text/css" />
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<link href="{{asset('admin/global/plugins/fancybox/source/jquery.fancybox.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('admin/global/plugins/jquery-file-upload/blueimp-gallery/blueimp-gallery.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('admin/global/plugins/jquery-file-upload/css/jquery.fileupload.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('admin/global/plugins/jquery-file-upload/css/jquery.fileupload-ui.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('admin/global/plugins/select2/css/select2.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('admin/global/plugins/select2/css/select2-bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('admin/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('admin/global/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('admin/global/plugins/bootstrap-markdown/css/bootstrap-markdown.min.css')}}" rel="stylesheet" type="text/css" />
<!-- END PAGE LEVEL PLUGINS -->


<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('plugins/datatables/jquery.dataTables.min.css') }}">
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('plugins/datatables/dataTables.bootstrap.css') }}">

@stack('styles')

<!-- BEGIN THEME GLOBAL STYLES -->
<link href="{{asset('admin/global/css/components.min.css')}}" rel="stylesheet" id="style_components" type="text/css" />
<link href="{{asset('admin/global/css/plugins.min.css')}}" rel="stylesheet" type="text/css" />
<!-- END THEME GLOBAL STYLES -->
<!-- BEGIN PAGE LEVEL STYLES -->
<link href="{{asset('admin/apps/css/inbox.min.css')}}" rel="stylesheet" type="text/css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN THEME LAYOUT STYLES -->
<link href="{{asset('admin/layouts/layout/css/layout.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('admin/layouts/layout/css/themes/darkblue.min.css')}}" rel="stylesheet" type="text/css" id="style_color" />
<link href="{{asset('admin/layouts/layout/css/custom.min.css')}}" rel="stylesheet" type="text/css" />

resources/views/admin/partials/theme-design.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 12/2/2017
 * Time: 10:36 PM
 */
?>
<!---->
{{--<!-- BEGIN THEME PANEL -->--}}
{{--<div class="theme-panel hidden-xs hidden-sm">--}}
    {{--<div class="toggler"> </div>--}}
    {{--<div class="toggler-close"> </div>--}}
    {{--<div class="theme-options">--}}
        {{--<div class="theme-option theme-colors clearfix">--}}
            {{--<span> THEME COLOR </span>--}}
            {{--<ul>--}}
                {{--<li class="color-default current tooltips" data-style="default" data-container="body" data-original-title="Default"> </li>--}}
                {{--<li class="color-darkblue tooltips" data-style="darkblue" data-container="body" data-original-title="Dark Blue"> </li>--}}
                {{--<li class="color-blue tooltips" data-style="blue" data-container="body" data-original-title="Blue"> </li>--}}
                {{--<li class="color-grey tooltips" data-style="grey" data-container="body" data-original-title="Grey"> </li>--}}
                {{--<li class="color-light tooltips" data-style="light" data-container="body" data-original-title="Light"> </li>--}}
                {{--<li class="color-light2 tooltips" data-style="light2" data-container="body" data-html="true" data-original-title="Light 2"> </li>--}}
            {{--</ul>--}}
        {{--</div>--}}
        {{--<div class="theme-option">--}}
            {{--<span> Theme Style </span>--}}
            {{--<select class="layout-style-option form-control input-sm">--}}
                {{--<option value="square" selected="selected">Square corners</option>--}}
                {{--<option value="rounded">Rounded corners</option>--}}
            {{--</select>--}}
        {{--</div>--}}
        {{--<div class="theme-option">--}}
            {{--<span> Layout </span>--}}
            {{--<select class="layout-option form-control input-sm">--}}
                {{--<option value="fluid" selected="selected">Fluid</option>--}}
                {{--<option value="boxed">Boxed</option>--}}
            {{--</select>--}}
        {{--</div>--}}
        {{--<div class="theme-option">--}}
            {{--<span> Header </span>--}}
            {{--<select class="page-header-option form-control input-sm">--}}
                {{--<option value="fixed" selected="selected">Fixed</option>--}}
                {{--<option value="default">Default</option>--}}
            {{--</select>--}}
        {{--</div>--}}
        {{--<div class="theme-option">--}}
            {{--<span> Top Menu Dropdown</span>--}}
            {{--<select class="page-header-top-dropdown-style-option form-control input-sm">--}}
                {{--<option value="light" selected="selected">Light</option>--}}
                {{--<option value="dark">Dark</option>--}}
            {{--</select>--}}
        {{--</div>--}}
        {{--<div class="theme-option">--}}
            {{--<span> Sidebar Mode</span>--}}
            {{--<select class="sidebar-option form-control input-sm">--}}
                {{--<option value="fixed">Fixed</option>--}}
                {{--<option value="default" selected="selected">Default</option>--}}
            {{--</select>--}}
        {{--</div>--}}
        {{--<div class="theme-option">--}}
            {{--<span> Sidebar Menu </span>--}}
            {{--<select class="sidebar-menu-option form-control input-sm">--}}
                {{--<option value="accordion" selected="selected">Accordion</option>--}}
                {{--<option value="hover">Hover</option>--}}
            {{--</select>--}}
        {{--</div>--}}
        {{--<div class="theme-option">--}}
            {{--<span> Sidebar Style </span>--}}
            {{--<select class="sidebar-style-option form-control input-sm">--}}
                {{--<option value="default" selected="selected">Default</option>--}}
                {{--<option value="light">Light</option>--}}
            {{--</select>--}}
        {{--</div>--}}
        {{--<div class="theme-option">--}}
            {{--<span> Sidebar Position </span>--}}
            {{--<select class="sidebar-pos-option form-control input-sm">--}}
                {{--<option value="left" selected="selected">Left</option>--}}
                {{--<option value="right">Right</option>--}}
            {{--</select>--}}
        {{--</div>--}}
        {{--<div class="theme-option">--}}
            {{--<span> Footer </span>--}}
            {{--<select class="page-footer-option form-control input-sm">--}}
                {{--<option value="fixed">Fixed</option>--}}
                {{--<option value="default" selected="selected">Default</option>--}}
            {{--</select>--}}
        {{--</div>--}}
    {{--</div>--}}
{{--</div>--}}
<!-- END THEME PANEL -->