routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// email verify
Route::get('verify-registration/{id}', ['as' => 'verify.registration', 'uses' => 'Auth\RegisterController@verifyByUser']);

//Social Login

Route::get('/auth/{social}','Auth\LoginController@socialLogin')->where('social','twitter|facebook|linkedin|google|github|bitbucket');
Route::get('/auth/{social}/callback','Auth\LoginController@handleProviderCallback')->where('social','twitter|facebook|linkedin|google|github|bitbucket');


// Member Users

Route::group([
    'prefix' => 'member',
    'namespace' => 'Member',
    'middleware' => ['auth', 'role:member'],
    'as' => 'member.'
], function () {
    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
});


// Management or Admin Users

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => ['auth', 'role:admin'],
    'as' => 'admin.'
], function () {
    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
    Route::resource('roles','RoleController');
    Route::resource('permissions','PermissionController');
    Route::resource('users','UserController');

});

app/Models/Permission.php
<?php

namespace App\Models;

use Zizaco\Entrust\EntrustPermission;

class Permission extends EntrustPermission
{
    //
}

app/Http/Controllers/Admin/PermissionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Permission;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['permissions'] = Permission::latest()->paginate(10);

        return view('admin.permissions.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.permissions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:permissions',
            'display_name' => 'required|unique:permissions',
        ]);

        $permission = new Permission();
        $permission->name         = strtolower($request->input('name'));
        $permission->display_name = $request->input('display_name');;
        $permission->description  = $request->input('description');; // optional
        $permission->save();

        return back()->with('status', ['type' => 'success', 'message' => 'Successfully Saved']);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['permission'] = Permission::findOrFail($id);
        return view('admin.permissions.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|unique:permissions,name,'. $id,
            'display_name' => 'required|unique:permissions,display_name,'. $id,
        ]);

        $permission = Permission::find($id);
        $permission->name        = strtolower($request->input('name'));
        $permission->display_name = $request->input('display_name');
        $permission->description  = $request->input('description');
        $permission->save();

        return back()->with('status', ['type' => 'success', 'message' => 'Successfully Updated']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('permission_role')->where('permission_id', $id)->delete();
        $permission = Permission::find($id);
        $permission->delete();

        return $this->index();
    }
}

resources/views/admin/permissions/_form.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 1/1/2018
 * Time: 11:37 PM
 */
?>

@if(!isset($permission))
<div class="row">
    <div class="col-md-6 col-lg-6  col-sm-12 col-xs-12 form-group {{ $errors->has('name') ? 'has-error' : '' }} ">
        {!! Form::label('name', 'Name') !!} <span class="required red"> * </span>
        <div class="form-group">
            {!! Form::text('name',null,['class'=>'form-control','placeholder'=>'Name']); !!}
        </div>
        {!! $errors->first('name', '<span class="help-block red"><strong>:message</strong></span>') !!}
    </div>
</div>
@endif

<div class="row">
    <div class="col-md-6 col-lg-6  col-sm-12 col-xs-12 form-group {{ $errors->has('display_name') ? 'has-error' : '' }} ">
        {!! Form::label('display_name', 'Display Name') !!} <span class="required red"> * </span>
        <div class="form-group">
            {!! Form::text('display_name',null,['class'=>'form-control','placeholder'=>'Display Name']); !!}
        </div>
        {!! $errors->first('display_name', '<span class="help-block red"><strong>:message</strong></span>') !!}
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-lg-6  col-sm-12 col-xs-12 form-group">
        {!! Form::label('description', 'Description') !!}
        <div class="form-group">
            {!! Form::textarea('description',null,['class'=>'form-control','placeholder'=>'Description', 'rows' =>2]); !!}
        </div>
        {!! $errors->first('description', '<span class="help-block red"><strong>:message</strong></span>') !!}
    </div>
</div>

<div class="row">
    <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12 text-right">
        <button type="submit" class="btn green">Save</button>
        <button type="reset" class="btn red">Reset</button>
    </div>
</div>

resources/views/admin/permissions/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 1/1/2018
 * Time: 11:38 PM
 */


$data['breadcrumb'] = [
    [
        'name' => 'Home',
        'href' => route('admin.dashboard'),
        'icon' => 'fa fa-home',
    ],
    [
        'name' => 'Permissions',
        'href' => route('admin.permissions.index'),
    ],
    [
        'name' => 'Add Permission',
    ],
];

$data['data'] = [
    'name' => 'Permissions',
    'title'=>'Add Permission',
    'heading' => 'Add Permission',
];

?>

@extends('admin.layout.master', $data)

@section('contents')
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">

            @include('common._alert')

            <div class="portlet light">

                <div class="portlet-body form">
                    {!! Form::open(['route' => 'admin.permissions.store', 'method' => 'POST', 'role'=>'form' ]) !!}

                    <div class="form-body">
                        @include('admin.permissions._form')
                    </div>

                    {!! Form::close() !!}
                </div>
                <!-- END SAMPLE FORM PORTLET-->
            </div>
        </div>
    </div>
@endsection

resources/views/admin/permissions/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 1/1/2018
 * Time: 11:37 PM
 */


$data['breadcrumb'] = [
    [
        'name' => 'Home',
        'href' => route('admin.dashboard'),
        'icon' => 'fa fa-home',
    ],
    [
        'name' => 'Permissions',
        'href' => route('admin.permissions.index'),
    ],
    [
        'name' => 'Edit',
    ],
];

$data['data'] = [
    'name' => 'Permissions',
    'title'=>'Edit Permission',
    'heading' => 'Edit Permission',
];

?>

@extends('admin.layout.master', $data)

@section('contents')
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
            <!-- BEGIN SAMPLE FORM PORTLET-->
            @include('common._alert')

            <div class="portlet light">

                <div class="portlet-body form">
                    {!! Form::model($permission, ['route' => ['admin.permissions.update', $permission],  'method' => 'put']) !!}

                    <div class="form-body">
                        @include('admin.permissions._form')
                    </div>

                    {!! Form::close() !!}
                </div>
                <!-- END SAMPLE FORM PORTLET-->
            </div>
        </div>
    </div>
@endsection

resources/views/admin/permissions/index.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 1/1/2018
 * Time: 11:37 PM
 */


$data['breadcrumb'] = [
    [
        'name' => 'Home',
        'href' => route('admin.dashboard'),
        'icon' => 'fa fa-home',
    ],
    [
        'name' => 'Permissions',
        'href' => route('admin.permissions.index'),
    ],
    [
        'name' => 'Index',
    ],
];

$data['data'] = [
    'name' => 'Permissions',
    'title'=>'List Of Permissions',
    'heading' => 'List Of Permissions',
];

?>

@extends('admin.layout.master', $data)

@section('contents')

    <div class="portlet light">

        <div class="portlet-body form">
            <a href="{{ route('admin.permissions.create') }}" class="btn green"> <i class="fa fa-plus"> Add Permission </i></a>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
    </div>
    <div class="row">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        @include('common._alert')

        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
            <!-- BEGIN SAMPLE FORM PORTLET-->

            <div class="table-responsive">
                <table class="table table-striped">
                    <tr>
                        <td> # </td>
                        <td> Display Name </td>
                        <td> Name </td>
                        <td> Manage </td>
                    </tr>
                    @foreach( $permissions as $permission)
                        <tr>
                            <td> {{ $loop->index + 1 }} </td>
                            <td> {{ $permission->display_name }} </td>
                            <td> {{ $permission->name }} </td>
                            <td>
                                <a href="{{ route('admin.permissions.edit', $permission->id) }}" class="btn btn-xs btn-success">
                                    <i class="fa fa-pencil"></i>
                                </a>

                                <a href="javascript:void(0);" class="btn btn-xs btn-danger delete-confirm" data-target="{{  route('admin.permissions.destroy', $permission->id) }}">
                                    <i class="fa fa-times"></i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    <tr>
                        <td colspan="4" class="text-right">
                            {{ $permissions->links() }}
                        </td>
                    </tr>

                </table>
            </div>
        </div>
    </div>
@endsection